import { useEffect, useMemo, useState } from 'react'
import { Link, useRouter } from '../router/Router'
import { useApp } from '../context/AppContext'
import { mentors, opportunities, projects, showcaseCourses } from '../data/platformData'
import { errorMessage } from '../services/api'
import './Platform.css'

const Icon = ({ children }) => <span className="p-icon" aria-hidden="true">{children}</span>
const SectionHead = ({ eyebrow, title, copy, action }) => <div className="p-section-head"><div><span className="p-eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>{action}</div>

export function CourseCard({ course }) {
  return <article className="p-course-card">
    <Link to={`/courses/${course.id}`} className={`p-course-cover tone-${course.tone || Number(course.id) % 4}`}><span>{course.category || course.subject || 'Professional skills'}</span><strong>{course.code || `LIB-COURSE-${String(course.id).padStart(3, '0')}`}</strong><i aria-hidden="true">{course.category === 'Design' ? '◐' : course.category === 'Data' ? '▥' : '⌘'}</i></Link>
    <div className="p-course-body"><div className="p-meta"><span>{course.level || course.difficulty || 'Beginner'}</span><span>★ {course.rating || 'New'}</span></div><h3><Link to={`/courses/${course.id}`}>{course.title}</Link></h3><p>{course.description}</p><div className="p-course-skills">{(course.skills||[course.category||course.subject||'Professional skill','Applied project']).slice(0,2).map(skill=><span key={skill}>{skill}</span>)}</div><div className="p-instructor"><span>{(course.instructor || 'Local instructor').split(' ').map(x=>x[0]).slice(0,2).join('')}</span><small>{course.instructor || 'Local instructor'}</small></div><div className="p-card-foot"><span>{course.duration || `${course.lessons_count || 0} lessons`}</span><strong>{course.price ? `${course.price} LYD` : 'View course'} · →</strong></div></div>
  </article>
}

export function HomePage() {
  const { user } = useApp()
  return <main className="p-home">
    <section className="p-hero"><div className="wrap p-hero-grid"><div className="p-hero-copy"><span className="p-eyebrow">Libya's platform for practical learning</span><h1>Build skills that move your future <em>forward.</em></h1><p>Learn from experienced local instructors, apply your knowledge to real projects, and connect with opportunities across Libya.</p><div className="p-actions"><Link className="btn btn-primary" to="/courses">Explore courses <span>→</span></Link><Link className="btn btn-ghost" to="/projects">Browse real projects</Link></div><div className="p-trust"><span>✓ Local instructors</span><span>✓ Practical projects</span><span>✓ Verifiable certificates</span></div></div><div className="p-hero-visual"><div className="p-visual-grid"><article className="p-feature-panel"><span className="p-live">● LEARNING PATH</span><h3>Digital Skills for Work</h3><div className="p-progress"><span style={{width:'68%'}} /></div><small>12 of 18 lessons completed</small></article><article className="p-mini-panel"><Icon>✓</Icon><div><strong>Project reviewed</strong><small>Portfolio website</small></div></article><article className="p-mini-panel opportunity"><Icon>↗</Icon><div><strong>Opportunity matched</strong><small>Frontend internship · Tripoli</small></div></article></div><div className="p-arabic-mark" lang="ar" dir="rtl">تعلّم · طبّق · اكسب</div></div></div></section>

    <section className="p-proof"><div className="wrap"><span>Learning built for Libya</span>{['Students & graduates','Instructors & mentors','Schools & universities','Government & organizations'].map(x=><strong key={x}>{x}</strong>)}</div></section>

    <section className="p-section wrap"><SectionHead eyebrow="Explore learning" title="Skills for the work that matters now" copy="Focused pathways designed around practical outcomes—not passive watching." action={<Link to="/courses">View all courses →</Link>} /><div className="p-course-grid">{showcaseCourses.slice(0,3).map(c=><CourseCard key={c.id} course={c}/>)}</div></section>

    <section className="p-section p-journey"><div className="wrap"><SectionHead eyebrow="Our difference" title="Learn → Apply → Earn" copy="One connected journey from your first lesson to demonstrable experience."/><div className="p-journey-grid">{[
      ['01','Learn','Build career-relevant skills with structured courses and local instructors.'],['02','Apply','Practice through assignments and real briefs. Build work you can show.'],['03','Get feedback','Work with instructors and mentors to improve your professional standard.'],['04','Earn','Receive a certificate and connect with internships, paid tasks and jobs.']
    ].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>

    <section className="p-section wrap"><SectionHead eyebrow="Built for every learner" title="A platform for national capability"/><div className="p-audience-grid">{[
      ['For learners','Learn flexibly, build a portfolio and access real opportunities.','Explore learning','/courses'],['For instructors','Create high-quality courses, mentor talent and measure outcomes.','Start teaching',user?'/dashboard':'/signup'],['For organizations','Develop teams through targeted, measurable professional training.','Discuss training','/services']
    ].map(([t,c,a,to],i)=><article key={t} className={`audience-${i}`}><span>{i===0?'◎':i===1?'◇':'▦'}</span><h3>{t}</h3><p>{c}</p><Link to={to}>{a} →</Link></article>)}</div></section>

    <section className="p-section p-cert-section"><div className="wrap p-cert-grid"><div><span className="p-eyebrow">Trusted achievement</span><h2>Credentials backed by completed work</h2><p>Certificates are issued after course requirements are met and remain linked to the learner's professional profile. We make no unconfirmed claims of government recognition.</p><Link className="btn btn-ghost" to="/certificates">View certificate records</Link></div><div className="p-certificate-preview"><div className="p-cert-logo">MISR<span>.</span></div><small>CERTIFICATE OF COMPLETION</small><h3>Professional Web Development</h3><p>Awarded for successful completion of lessons, assessment and applied project.</p><strong>LIB-EDU-2026-8F2A17</strong><span className="p-seal">✓</span></div></div></section>

    <section className="p-section wrap"><SectionHead eyebrow="Local impact" title="Learning journeys that create momentum"/><div className="p-stories"><blockquote>“The final project gave me something credible to discuss in interviews—not just another completed video course.”<footer>— Mariam, junior designer in Benghazi</footer></blockquote><blockquote>“Our training cohort could see the link between each module, the applied task and the expected workplace outcome.”<footer>— Organization training coordinator</footer></blockquote></div></section>

    <section className="p-final-cta"><div className="wrap"><span className="p-eyebrow">Your next step starts here</span><h2>Learn with purpose. Build with confidence.</h2><p>Join a Libyan learning community designed to turn knowledge into capability.</p><div className="p-actions"><Link className="btn btn-primary" to="/courses">Find your course</Link><Link className="btn btn-ghost" to="/about">Learn about the platform</Link></div></div></section>
  </main>
}

export function CoursesPage() {
  const { api, user } = useApp(); const [query,setQuery]=useState(''); const [level,setLevel]=useState('All levels'); const [category,setCategory]=useState('All categories'); const [remote,setRemote]=useState([])
  useEffect(()=>{ api.get(user?'/courses':'/public/courses').then(r=>setRemote(r.data?.data||[])).catch(()=>{}) },[api,user])
  const source=remote.length?remote.map((x,i)=>({...showcaseCourses[i%showcaseCourses.length],...x,code:`LIB-${(x.subject||'SKILL').slice(0,4).toUpperCase()}-${String(x.id).padStart(3,'0')}`})):showcaseCourses
  const shown=useMemo(()=>source.filter(c=>(!query||`${c.title} ${c.description} ${c.instructor}`.toLowerCase().includes(query.toLowerCase()))&&(level==='All levels'||(c.level||c.difficulty)?.toLowerCase()===level.toLowerCase())&&(category==='All categories'||(c.category||c.subject)===category)),[source,query,level,category])
  return <main className="p-page"><section className="p-page-hero"><div className="wrap"><span className="p-eyebrow">Course marketplace</span><h1>Build your next professional skill</h1><p>Career-focused courses, applied assignments and guidance from instructors who understand the local context.</p><div className="p-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by skill, course or instructor"/><button>Search</button></div></div></section><div className="wrap p-catalog"><aside><strong>Filter courses</strong><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All categories','Programming','Design','Data','Government Training'].map(x=><option key={x}>{x}</option>)}</select></label><label>Skill level<select value={level} onChange={e=>setLevel(e.target.value)}>{['All levels','Beginner','Intermediate','Advanced'].map(x=><option key={x}>{x}</option>)}</select></label><label>Duration<select><option>Any duration</option><option>Under 4 weeks</option><option>4–8 weeks</option><option>8+ weeks</option></select></label><label>Price<select><option>Any price</option><option>Free</option><option>Under 300 LYD</option><option>300+ LYD</option></select></label></aside><section className="p-catalog-results"><div className="p-result-head"><div><strong>{shown.length} courses</strong><span> available</span></div><select aria-label="Sort courses"><option>Most relevant</option><option>Highest rated</option><option>Newest</option></select></div><div className="p-course-grid">{shown.map(c=><CourseCard key={c.id} course={c}/>)}</div>{!shown.length&&<div className="p-empty">No courses match these filters. Try a broader search.</div>}</section></div></main>
}

export function CourseDetailsPage({ id }) {
  const { api,user }=useApp(); const { navigate }=useRouter(); const [remote,setRemote]=useState(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('')
  useEffect(()=>{api.get(user?`/courses/${id}`:`/public/courses/${id}`).then(r=>setRemote(r.data)).catch(()=>{})},[api,user,id])
  const base=showcaseCourses.find(c=>String(c.id)===String(id))||showcaseCourses[0]; const course=remote?{...base,...remote,code:`LIB-${(remote.subject||'SKILL').slice(0,4).toUpperCase()}-${String(remote.id).padStart(3,'0')}`}:base; const lessons=course.lessons||Array.from({length:6},(_,i)=>({id:i+1,title:['Foundations and outcomes','Core tools and workflow','Guided practical exercise','Working with a real brief','Quality review and feedback','Final applied project'][i],duration_minutes:[35,48,55,42,38,90][i]}))
  const enroll=async()=>{if(!user){navigate('/login');return}setBusy(true);try{const{data}=await api.post(`/courses/${id}/register`);setNotice(data.message);if(data.status!=='approved')setTimeout(()=>navigate('/registrations'),700)}catch(e){setNotice(errorMessage(e))}finally{setBusy(false)}}
  return <main className="p-page p-course-detail"><section className={`p-course-banner tone-${course.tone||'violet'}`}><div className="wrap"><div><span className="p-eyebrow">{course.category||course.subject||'Professional skills'} · {course.code}</span><h1>{course.title}</h1><p>{course.description}</p><div className="p-detail-meta"><span>★ {course.rating||'New'} rating</span><span>{course.level||course.difficulty}</span><span>{course.duration||`${lessons.length} lessons`}</span><span>Arabic / English support</span></div><div className="p-instructor large"><span>{(course.instructor||'Local Instructor').split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><small>Course instructor</small><strong>{course.instructor||'Local instructor'}</strong></div></div></div><aside><div className="p-video-placeholder"><span>▶</span><small>Course overview</small></div><strong className="p-price">{course.price?`${course.price} LYD`:'Enrollment available'}</strong><button className="btn btn-primary" disabled={busy} onClick={enroll}>{busy?'Adding…':course.enrollment?'Continue learning':'Enroll in course'}</button>{notice&&<p className="p-notice">{notice}</p>}<small>Includes lessons, project feedback and certificate eligibility.</small></aside></div></section><div className="wrap p-detail-layout"><article><section className="p-detail-section"><h2>What you will learn</h2><div className="p-outcomes">{(course.outcomes||base.outcomes).map(x=><p key={x}>✓ <span>{x}</span></p>)}</div></section><section className="p-detail-section"><h2>Course curriculum</h2><p>{lessons.length} structured lessons · progress saved automatically</p><div className="p-curriculum">{lessons.map((l,i)=><div key={l.id}><span>{String(i+1).padStart(2,'0')}</span><strong>{l.title}</strong><small>{l.duration_minutes||30} min</small></div>)}</div></section><section className="p-detail-section"><h2>Applied project</h2><div className="p-project-callout"><Icon>↗</Icon><div><strong>Complete a real-world brief</strong><p>Submit a professional deliverable, receive instructor feedback and add the approved result to your learner portfolio.</p></div></div></section></article><aside className="p-side-info"><h3>This course includes</h3>{['Structured video/content lessons','Downloadable resources','Practical assignment','Applied portfolio project','Instructor feedback','Certificate eligibility'].map(x=><p key={x}>✓ {x}</p>)}<hr/><h3>Requirements</h3><p>A computer, reliable internet access and time for weekly practice. No prior professional experience is required for beginner pathways.</p></aside></div></main>
}

function ListingPage({ kind }) {
  const {api,user}=useApp(); const {navigate}=useRouter(); const projectMode=kind==='projects'; const [list,setList]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('')
  const load=()=>{setLoading(true);api.get(`/public/${kind}`,{params:{q:query||undefined}}).then(r=>setList(r.data?.data||[])).catch(e=>setNotice(errorMessage(e))).finally(()=>setLoading(false))}
  useEffect(load,[kind]); const apply=async id=>{if(!user){navigate('/login');return}try{await api.post(`/${kind}/${id}/apply`,{cover_note:'Application submitted from MEHARA learner profile.'});setNotice('Application submitted successfully.')}catch(e){setNotice(errorMessage(e))}}
  return <main className="p-page"><section className="p-page-hero compact"><div className="wrap"><span className="p-eyebrow">{projectMode?'Real-world experience':'Career pathways'}</span><h1>{projectMode?'Build experience through projects':'Find your next opportunity'}</h1><p>{projectMode?'Practice your skills on structured briefs, submit your work and receive feedback.':'Discover internships, freelance projects, jobs and paid tasks connected to your skills.'}</p><form className="p-search" onSubmit={e=>{e.preventDefault();load()}}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${kind}, skills or categories`}/><button>Search</button></form>{notice&&<p className="p-notice">{notice}</p>}</div></section><div className="wrap p-list-layout"><aside className="p-filter-row"><span>{list.length} active listings</span><span>Verified MEHARA workflow</span></aside><section className="p-listings">{loading?<div className="p-empty">Loading current listings…</div>:list.map(item=>{const skills=Array.isArray(item.skills)?item.skills:JSON.parse(item.skills||'[]');return <article key={item.id}><div className="p-list-icon">{projectMode?'◇':'↗'}</div><div className="p-list-main"><span className="p-eyebrow">{item.category||item.type} · MEH-{projectMode?'PRJ':'OPP'}-{String(item.id).padStart(4,'0')}</span><h2>{item.title}</h2><p>{item.description}</p><div className="p-tags">{skills.map(s=><span key={s}>{s}</span>)}</div><div className="p-list-meta">{projectMode?<><span>{item.difficulty}</span><span>{item.deadline?`Deadline ${new Date(item.deadline).toLocaleDateString()}`:'Flexible deadline'}</span><span>{item.applicants_count||0} applicants</span></>:<><span>{item.organization}</span><span>{item.is_remote?'Remote':item.location||'On-site'}</span><span>{item.budget_max_lyd?`Up to ${item.budget_max_lyd} LYD`:'Budget on review'}</span></>}</div></div><button className="btn btn-primary" onClick={()=>apply(item.id)}>{projectMode?'Apply to project':'Apply now'}</button></article>})}{!loading&&!list.length&&<div className="p-empty"><strong>No active listings yet.</strong><p>New verified listings will appear here when published.</p></div>}</section></div></main>
}
export const ProjectsPage=()=> <ListingPage kind="projects"/>
export const OpportunitiesPage=()=> <ListingPage kind="opportunities"/>

export function MentorshipPage(){const{api,user}=useApp();const{navigate}=useRouter();const[list,setList]=useState([]),[notice,setNotice]=useState('');useEffect(()=>{api.get('/public/mentors').then(r=>setList(r.data||[])).catch(e=>setNotice(errorMessage(e)))},[api]);const book=async id=>{if(!user){navigate('/login');return}const scheduled_at=new Date(Date.now()+86400000).toISOString();try{await api.post(`/mentors/${id}/book`,{scheduled_at,goals:'Portfolio and career guidance'});setNotice('Mentorship request sent. You can track it from your dashboard.')}catch(e){setNotice(errorMessage(e))}};return <main className="p-page"><section className="p-page-hero compact"><div className="wrap"><span className="p-eyebrow">Personal guidance</span><h1>Learn with someone who's been there</h1><p>Connect with experienced professionals for portfolio feedback, career direction and practical support.</p>{notice&&<p className="p-notice">{notice}</p>}</div></section><section className="p-section wrap"><SectionHead eyebrow="Mentor directory" title="Find the right perspective"/><div className="p-mentor-grid">{list.map(m=>{const expertise=Array.isArray(m.expertise)?m.expertise:JSON.parse(m.expertise||'[]');return <article key={m.id}><div className="p-mentor-avatar">{m.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span className="p-status-dot">● {m.availability}</span><h3>{m.name}</h3><strong>{m.headline}</strong><p>{expertise.join(' · ')} · {m.experience_years} years</p><button className="btn btn-primary" onClick={()=>book(m.id)}>Request session</button></article>})}{!list.length&&<div className="p-empty">Published mentors will appear here.</div>}</div></section></main>}

export function ServicesPage(){const{api,user}=useApp();const{navigate}=useRouter();const[category,setCategory]=useState('Design'),[description,setDescription]=useState(''),[notice,setNotice]=useState('');const services=[['Design','Brand identity and visual communication'],['Research','Research structuring and data support'],['Presentations','Professional decks and projector slides'],['Development','Websites and digital products'],['Digital Services','Practical support for digital workflows'],['Organization Training','Custom learning paths for teams']];const submit=async e=>{e.preventDefault();if(!user){navigate('/login');return}try{await api.post('/service-requests',{category,title:`${category} service request`,description});setDescription('');setNotice('Your request was submitted to the MEHARA team.')}catch(err){setNotice(errorMessage(err))}};return <main className="p-page"><section className="p-page-hero"><div className="wrap"><span className="p-eyebrow">Professional services</span><h1>Expert support for clear, credible and effective work</h1><p>Submit a structured request and track it through the MEHARA management workflow.</p></div></section><section className="p-section wrap"><div className="p-service-grid">{services.map(([t,c],i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{c}</p><button className="btn btn-ghost" onClick={()=>setCategory(t)}>Select service →</button></article>)}</div><form className="meh-workflow-card platform-form" onSubmit={submit}><h2>Request a service</h2><label className="platform-field">Service<select value={category} onChange={e=>setCategory(e.target.value)}>{services.map(([t])=><option key={t}>{t}</option>)}</select></label><label className="platform-field">What do you need?<textarea required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the outcome, audience and deadline"/></label><button className="btn btn-primary">Submit request</button>{notice&&<p className="p-notice">{notice}</p>}</form></section></main>}

export function LiveClassesPage(){const {api}=useApp(); const [events,setEvents]=useState([]);useEffect(()=>{api.get('/calendar-events').then(r=>setEvents(r.data||[])).catch(()=>{})},[api]);return <main className="p-page"><section className="p-page-hero compact"><div className="wrap"><span className="p-eyebrow">Live learning</span><h1>Upcoming live classes</h1><p>Instructor-led sessions, project reviews and mentor workshops. Phase 1 sessions use approved external meeting links.</p></div></section><section className="p-section wrap p-live-list">{events.length?events.map(e=><article key={e.id}><div className="p-date"><strong>{new Date(e.starts_at).getDate()}</strong><span>{new Date(e.starts_at).toLocaleString('en',{month:'short'})}</span></div><div><span className="p-eyebrow">{e.event_type}</span><h3>{e.title}</h3><p>{new Date(e.starts_at).toLocaleString()} {e.ends_at&&` · until ${new Date(e.ends_at).toLocaleTimeString()}`}</p></div><button className="btn btn-primary">View session</button></article>):<div className="p-empty"><strong>No live classes scheduled yet.</strong><p>New sessions will appear here when an instructor publishes them.</p></div>}</section></main>}
