import { useEffect,useState } from 'react'
import { Link } from '../../router/Router'
import { useApp } from '../../context/AppContext'
import { errorMessage } from '../../services/api'

const tabs=['overview','courses','users','subscriptions','notifications']
export default function AdminMinistryDashboardPage(){const{api,language}=useApp();const[tab,setTab]=useState('overview'),[summary,setSummary]=useState({}),[items,setItems]=useState([]),[notice,setNotice]=useState('');const[announcement,setAnnouncement]=useState({title:'',message:'',audience:'all'});const t=(ar,en)=>language==='ar'?ar:en
 const load=()=>{setItems([]);const endpoint=tab==='overview'?'/admin/report-summary':tab==='courses'?'/courses':tab==='users'?'/admin/users':tab==='subscriptions'?'/admin/subscriptions':null;if(endpoint)api.get(endpoint).then(r=>tab==='overview'?setSummary(r.data):setItems(r.data?.data||r.data||[])).catch(e=>setNotice(errorMessage(e)))};useEffect(load,[tab])
 const patch=async(url,data)=>{try{await api.patch(url,data);setNotice(t('تم حفظ التغيير.','Change saved.'));load()}catch(e){setNotice(errorMessage(e))}};const remove=async(url)=>{if(!confirm(t('هل تريد حذف هذا السجل؟','Delete this record?')))return;try{await api.delete(url);setNotice(t('تم حذف السجل.','Record deleted.'));load()}catch(e){setNotice(errorMessage(e))}};const send=async e=>{e.preventDefault();try{const{data}=await api.post('/admin/notifications',announcement);setNotice(`${data.message} ${data.recipients}`);setAnnouncement({...announcement,title:'',message:''})}catch(e){setNotice(errorMessage(e))}}
 return <main className="admin-command"><aside className="admin-command-nav"><div><strong>MEHARA</strong><small>{t('مركز التحكم','CONTROL CENTER')}</small></div><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{t({overview:'نظرة عامة',courses:'الدورات',users:'المستخدمون',subscriptions:'الاشتراكات',notifications:'الإشعارات'}[x],x[0].toUpperCase()+x.slice(1))}</button>)}</nav><Link to="/admin/content">{t('استوديو المحتوى','Content studio')} →</Link><Link to="/admin/registrations">{t('مراجعة التسجيلات','Registration reviews')} →</Link></aside><section className="admin-command-main"><header><div><span className="p-eyebrow">MEHARA ADMIN</span><h1>{t('إدارة المنصة','Platform management')}</h1><p>{t('إدارة المحتوى والمستخدمين والتعلم من مساحة واحدة.','Manage content, users and learning operations from one workspace.')}</p></div><Link className="btn btn-primary" to="/instructor/courses/create">{t('إضافة دورة','Add course')}</Link></header>{notice&&<p className="p-notice">{notice}</p>}
 {tab==='overview'&&<><div className="admin-metric-grid">{Object.entries(summary).map(([k,v])=><article key={k}><span>{k.replaceAll('_',' ')}</span><strong>{k.includes('lyd')?`${v} LYD`:v}</strong></article>)}</div><div className="admin-quick-grid"><Link to="/admin/content"><h3>{t('نشر الأخبار والملفات','Publish news & files')}</h3><p>{t('أضف تحديثات ومواد تعليمية.','Add updates and learning resources.')}</p></Link><Link to="/admin/registrations"><h3>{t('مراجعة المدفوعات','Review payments')}</h3><p>{t('وافق أو ارفض طلبات التسجيل.','Approve or reject registrations.')}</p></Link><Link to="/instructor/courses"><h3>{t('إدارة التعلم','Manage learning')}</h3><p>{t('حرر الدورات والدروس والمشاريع.','Edit courses, lessons and projects.')}</p></Link></div></>}
 {tab==='courses'&&<div className="admin-table-shell"><table><thead><tr><th>{t('الدورة','Course')}</th><th>{t('الرمز','Code')}</th><th>{t('السعر','Price')}</th><th>{t('الحالة','Status')}</th><th>{t('الإجراء','Action')}</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.course_code||'—'}</td><td>{x.price_lyd||0} LYD</td><td><button className="status-pill" onClick={()=>patch(`/courses/${x.id}`,{is_published:!x.is_published})}>{x.is_published?t('منشورة','Published'):t('مسودة','Draft')}</button></td><td><Link to={`/instructor/courses/${x.id}/edit`}>{t('تعديل','Edit')}</Link> · <button onClick={()=>remove(`/courses/${x.id}`)}>{t('أرشفة','Archive')}</button></td></tr>)}</tbody></table></div>}
 {tab==='users'&&<div className="admin-table-shell"><table><thead><tr><th>{t('الاسم','Name')}</th><th>{t('البريد','Email')}</th><th>{t('الدور','Role')}</th><th>{t('الحالة','Status')}</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td><select value={x.role} onChange={e=>patch(`/admin/users/${x.id}`,{role:e.target.value})}><option value="student">Learner</option><option value="teacher">Instructor</option><option value="admin">Admin</option></select></td><td><button onClick={()=>patch(`/admin/users/${x.id}`,{status:x.status==='active'?'suspended':'active'})}>{x.status}</button></td><td><button className="danger-action" onClick={()=>remove(`/admin/users/${x.id}`)}>{t('حذف','Delete')}</button></td></tr>)}</tbody></table></div>}
 {tab==='subscriptions'&&<div className="admin-table-shell"><table><thead><tr><th>{t('المستخدم','User')}</th><th>{t('الخطة','Plan')}</th><th>{t('القيمة','Amount')}</th><th>{t('الحالة','Status')}</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}<small>{x.email}</small></td><td>{x.plan_name}</td><td>{x.price_cents/100} {x.currency}</td><td><select value={x.status} onChange={e=>patch(`/admin/subscriptions/${x.id}`,{status:e.target.value})}>{['pending_provider','active','paused','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}
 {tab==='notifications'&&<form className="admin-compose" onSubmit={send}><h2>{t('إرسال إشعار','Send notification')}</h2><label>{t('المستلمون','Audience')}<select value={announcement.audience} onChange={e=>setAnnouncement({...announcement,audience:e.target.value})}><option value="all">{t('الجميع','Everyone')}</option><option value="students">{t('المتعلمون','Learners')}</option><option value="teachers">{t('المدربون','Instructors')}</option></select></label><label>{t('العنوان','Title')}<input required value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></label><label>{t('الرسالة','Message')}<textarea required value={announcement.message} onChange={e=>setAnnouncement({...announcement,message:e.target.value})}/></label><button className="btn btn-primary">{t('إرسال الآن','Send now')}</button></form>}
 </section></main>}
