import { useEffect, useMemo, useState } from 'react'
import { useApp } from '../../context/AppContext'
import { useRouter } from '../../router/Router'
import { errorMessage } from '../../services/api'
import './CourseEditorPage.css'

const steps=['Basic information','Course details','Visual identity','Lessons','Applied project','Assessment','Pricing','Review & publish']
const Field=({label,children})=><label className="platform-field">{label}{children}</label>

export default function CourseEditorPage(){
  const {api}=useApp(); const {path}=useRouter(); const courseId=path.match(/^\/instructor\/courses\/(\d+)\/edit$/)?.[1]; const [step,setStep]=useState(0),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const [form,setForm]=useState({title:'',description:'',difficulty:'beginner',grade_level:'Professional learner',language:'both',learning_objectives:'',requirements:'',price_lyd:0,course_code:'',thumbnail_path:'',is_published:false})
  const [lessons,setLessons]=useState([{title:'',summary:'',content:'',video_url:'',duration_minutes:30}])
  const [project,setProject]=useState({title:'',description:'',category:'Applied learning',skills:'',difficulty:'beginner'})
  useEffect(()=>{if(!courseId)return;api.get(`/courses/${courseId}`).then(({data})=>{setForm(v=>({...v,...data,price_lyd:data.price_lyd||0,course_code:data.course_code||'',thumbnail_path:data.thumbnail_path||''}));if(data.lessons?.length)setLessons(data.lessons)}).catch(e=>setNotice(errorMessage(e)))},[courseId,api])
  const update=(key,value)=>setForm(v=>({...v,[key]:value})); const updateLesson=(i,key,value)=>setLessons(v=>v.map((x,n)=>n===i?{...x,[key]:value}:x))
  const valid=useMemo(()=>form.title.trim()&&form.description.trim()&&lessons.some(x=>x.title.trim()),[form,lessons])
  const save=async()=>{setNotice('');setBusy(true);try{const payload={...form,price_lyd:Number(form.price_lyd)||0,course_code:form.course_code||null,lessons:lessons.filter(x=>x.title.trim()).map(x=>({...x,duration_minutes:Number(x.duration_minutes)||0}))};const{data:course}=courseId?await api.patch(`/courses/${courseId}`,payload):await api.post('/courses',payload);if(!courseId&&project.title.trim())await api.post('/projects',{course_id:course.id,...project,skills:project.skills.split(',').map(x=>x.trim()).filter(Boolean)});setNotice(`Course ${course.course_code||course.id} saved successfully.`)}catch(error){setNotice(errorMessage(error))}finally{setBusy(false)}}
  return <main className="p-page"><section className="p-page-hero compact"><div className="wrap"><span className="p-eyebrow">MEHARA instructor studio</span><h1>Create a professional course</h1><p>Build lessons, practical work, pricing and publishing settings in one guided workflow.</p></div></section><div className="wrap p-detail-layout"><aside className="p-side-info">{steps.map((label,index)=><button className="editor-step" key={label} onClick={()=>setStep(index)}><strong>{index===step?'●':'○'} {index+1}. {label}</strong></button>)}</aside><section className="p-detail-section"><h2>{steps[step]}</h2>
  {step===0&&<><Field label="Course title"><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Digital Skills for Work"/></Field><Field label="Course code"><input value={form.course_code} onChange={e=>update('course_code',e.target.value)} placeholder="Auto-generated if blank"/></Field><Field label="Short description"><textarea value={form.description} onChange={e=>update('description',e.target.value)}/></Field></>}
  {step===1&&<><Field label="Skill level"><select value={form.difficulty} onChange={e=>update('difficulty',e.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></Field><Field label="Audience"><input value={form.grade_level} onChange={e=>update('grade_level',e.target.value)}/></Field><Field label="Language"><select value={form.language} onChange={e=>update('language',e.target.value)}><option value="ar">Arabic</option><option value="en">English</option><option value="both">Arabic & English</option></select></Field><Field label="Learning objectives"><textarea value={form.learning_objectives} onChange={e=>update('learning_objectives',e.target.value)}/></Field><Field label="Requirements"><textarea value={form.requirements} onChange={e=>update('requirements',e.target.value)}/></Field></>}
  {step===2&&<><Field label="Thumbnail path or URL"><input value={form.thumbnail_path} onChange={e=>update('thumbnail_path',e.target.value)} placeholder="Professional 16:9 visual"/></Field><div className="p-project-callout"><span className="p-icon">◫</span><div><strong>Consistent course visual</strong><p>Use a professional image without logos or watermarks.</p></div></div></>}
  {step===3&&<>{lessons.map((lesson,i)=><div className="editor-lesson" key={i}><h3>Lesson {i+1}</h3><Field label="Title"><input value={lesson.title} onChange={e=>updateLesson(i,'title',e.target.value)}/></Field><Field label="Summary"><textarea value={lesson.summary} onChange={e=>updateLesson(i,'summary',e.target.value)}/></Field><Field label="Video URL"><input value={lesson.video_url} onChange={e=>updateLesson(i,'video_url',e.target.value)}/></Field><Field label="Duration (minutes)"><input type="number" min="0" value={lesson.duration_minutes} onChange={e=>updateLesson(i,'duration_minutes',e.target.value)}/></Field></div>)}<button className="btn btn-ghost" onClick={()=>setLessons(v=>[...v,{title:'',summary:'',content:'',video_url:'',duration_minutes:30}])}>+ Add lesson</button></>}
  {step===4&&<><Field label="Project title"><input value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/></Field><Field label="Project brief"><textarea value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/></Field><Field label="Required skills (comma separated)"><input value={project.skills} onChange={e=>setProject({...project,skills:e.target.value})}/></Field></>}
  {step===5&&<div className="p-project-callout"><span className="p-icon">✓</span><div><strong>Assessment workflow</strong><p>Quizzes, assignments and evaluated submissions are available from the instructor workspace after saving.</p></div></div>}
  {step===6&&<Field label="Course price (LYD)"><input type="number" min="0" value={form.price_lyd} onChange={e=>update('price_lyd',e.target.value)}/></Field>}
  {step===7&&<><div className="editor-review"><h3>{form.title||'Untitled course'}</h3><p>{form.description||'Add a course description.'}</p><p>{form.difficulty} · {lessons.filter(x=>x.title.trim()).length} lessons · {form.price_lyd||0} LYD</p></div><label className="checkbox"><input type="checkbox" checked={form.is_published} onChange={e=>update('is_published',e.target.checked)}/> Publish immediately</label></>}
  <div className="p-actions editor-actions"><button className="btn btn-ghost" disabled={!step} onClick={()=>setStep(step-1)}>Previous</button>{step<steps.length-1?<button className="btn btn-primary" onClick={()=>setStep(step+1)}>Continue</button>:<button className="btn btn-primary" disabled={!valid||busy} onClick={save}>{busy?'Saving…':'Save course'}</button>}</div>{notice&&<p className="p-notice">{notice}</p>}</section></div></main>
}
